### ISSUE TITLE
get_approve - not signing.

### ISSUE THREAD

**Issue by snub-fighter** [RichardAtCT/1inch_wrapper#7]
Was trying to approve busd spending with 1inch.   i made an extra function -> get_approve_with_contract   I dont like looking things up with token names because there can be duplicates.  Also removed the amount because amount is optional in 1inch api.  

A missing amount = infinite. 

        result = bsc_exchange.get_approve_with_contract(from_address=src,  decimal=decimal)  # get the swap transaction , AMOUNT + SLIPPAGE ARE FLOATS NOT STRING

```
{'data': '..............................ff',
 'gasPrice': '15000000000',
 'to': '0xe9e7cea3dedca5984780bafc599bd69add087d56',
 'value': '0'}
```

I tried to sign the tx  - even removed the build_tx piece to just sign and broadcast. 

```
result = helper.build_tx(result)  # prepare the transaction for signing, gas price defaults to fast.
    pprint(result)
    result = helper.sign_tx(result)  # sign the transaction using your private key
    pprint(result)
    result = helper.broadcast_tx(result)  # broadcast the transaction to the network and wait for the receipt.
    pprint(result)

```

```

    def get_approve(self, from_token_symbol: str, amount=None):
        from_address = self._token_to_address(from_token_symbol)
        amount_in_wei = Decimal(amount * 10 ** self.tokens[from_token_symbol]['decimals'])
        url = f'{self.base_url}/{self.version}/{self.chain_id}/approve/transaction'
        url = url + f"?tokenAddress={from_address}&amount={amount_in_wei}"
        result = self._get(url)
        return result

    def get_approve_with_contract(self, from_address: str, decimal: int, amount=None):
        url = f'{self.base_url}/{self.version}/{self.chain_id}/approve/transaction'
        if amount == None:
            url = url + f"?tokenAddress={from_address}"
        if amount != None:
            amount_in_wei = Decimal(amount * 10 ** decimal)
            url = url + f"?tokenAddress={from_address}&amount={amount_in_wei}"
        result = self._get(url)
        return result


```

**Comment by RichardAtCT** [comment]
What error are you getting when you try sign?

**Comment by RichardAtCT** [comment]
Ah I think I see the issue - the approve/transaction endpoint doesn't include the "gas" parameter. 
You will need to send your transaction via estimate_gas

something like (untested):

```
def build_tx(self, raw_tx, speed='high'):
        nonce = self.w3.eth.getTransactionCount(self.public_key)
        tx = raw_tx['tx']
        if tx['gas'] is None:
             tx['gas'] = self.w3.estimate_gas(tx}
        tx['nonce'] = nonce
        tx['to'] = self.w3.toChecksumAddress(tx['to'])
        tx['chainId'] = int(self.chain_id)
        tx['value'] = int(tx['value'])
        tx['gas'] = int(tx['gas'] * 1.25)
        if self.chain == 'ethereum' or self.chain == 'polygon' or self.chain == 'avalanche' or self.chain == 'gnosis':
            gas = self._get(self.gas_oracle+self.chain_id)
            # print(gas)
            # gas = requests.get(self.gas_oracle, params=self.chain_id)
            tx['maxPriorityFeePerGas'] = int(gas[speed]['maxPriorityFeePerGas'])
            tx['maxFeePerGas'] = int(gas[speed]['maxFeePerGas'])
            tx.pop('gasPrice')
        else:
            tx['gasPrice'] = int(tx['gasPrice'])
        return tx
```

**Comment by snub-fighter** [comment]
Ok - I deep dived on this and I got to the end.   Had to make a few changes....   its a little complicated.

1.  Using the get_approve failed on BSC and im not sure why but I added that _with_contract function as IMHO its more secure.
```
    def get_approve_with_contract(self, from_address: str, decimal: int, amount=None):
        url = f'{self.base_url}/{self.version}/{self.chain_id}/approve/transaction'
        if amount == None:
            url = url + f"?tokenAddress={from_address}"
        if amount != None:
            amount_in_wei = Decimal(amount * 10 ** decimal)
            url = url + f"?tokenAddress={from_address}&amount={amount_in_wei}"
        result = self._get(url)
        return result
```
2. build_tx - 
    a.     the 'to' needs to be above in order to convert the address to a proper checksummed address.
    b.  The results of get_approval only provide the following so trying to match against tx['gas] is None will always fail because there is no key 'gas
    ```
          {'data': '0x095.......fffffffffffffffffffffffffffffffff',
            'gasPrice': '15000000000',
             'to': '0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d',
             'value': '0'}
      ```
     c.  self.w3.estimate_gas(tx) -> fails because it wants self.w3.eth.estimate_gas(tx)  
          I have accounted for a non-existant ['gas'] key and/or == None
          
     Summary of build_tx changes.
     
     ```
     def build_tx(self, raw_tx, speed='high'):
        nonce = self.w3.eth.getTransactionCount(self.public_key)
        # tx = raw_tx['tx']
        tx = raw_tx # ['tx']
        tx['to'] = self.w3.toChecksumAddress(tx['to'])
        if 'gas' not in tx:  ### TEST LINE
            tx['gas'] = self.w3.eth.estimate_gas(tx) ### TEST LINE
            print('tx[\'gas\'] RESULTS {}'.format(tx['gas']))
        if tx['gas'] == None:
            tx['gas'] = self.w3.eth.estimate_gas(tx) ### TEST LINE
            print('tx[\'gas\'] RESULTS {}'.format(tx['gas']))
        tx['nonce'] = nonce
        tx['chainId'] = int(self.chain_id)
        tx['value'] = int(tx['value'])
        tx['gas'] = int(tx['gas'] * 1.25)
        if self.chain == 'ethereum' or self.chain == 'polygon' or self.chain == 'avalanche' or self.chain == 'gnosis':
            gas = self._get(self.gas_oracle+self.chain_id)
            # print(gas)
            # gas = requests.get(self.gas_oracle, params=self.chain_id)
            tx['maxPriorityFeePerGas'] = int(gas[speed]['maxPriorityFeePerGas'])
            tx['maxFeePerGas'] = int(gas[speed]['maxFeePerGas'])
            tx.pop('gasPrice')
        else:
            tx['gasPrice'] = int(tx['gasPrice'])
        return tx
         ```


3.  We are now at the broadcasting piece.   For somereason i am getting invalid sender and everything I can find points to chainId but that all looks correct.
```
Traceback (most recent call last):
  File "C:\Users\USER_USER\PycharmProjects\test_1inch_py\main.py", line 82, in <module>
    result = bsc_helper.broadcast_tx(result) #broadcast the transaction to the network and wait for the receipt.
  File "C:\Users\USER_USER\PycharmProjects\test_1inch_py\venv\lib\site-packages\oneinch_py\main.py", line 326, in broadcast_tx
    tx_hash = self.w3.eth.send_raw_transaction(signed_tx.rawTransaction)
  File "C:\Users\USER_USER\PycharmProjects\test_1inch_py\venv\lib\site-packages\web3\eth.py", line 831, in send_raw_transaction
    return self._send_raw_transaction(transaction)
  File "C:\Users\USER_USER\PycharmProjects\test_1inch_py\venv\lib\site-packages\web3\module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "C:\Users\USER_USER\PycharmProjects\test_1inch_py\venv\lib\site-packages\web3\manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "C:\Users\USER_USER\PycharmProjects\test_1inch_py\venv\lib\site-packages\web3\manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'invalid sender'}

```


The data that is being packaged is shown below.  iVE MADE NO CHANGES TO broadcast_tx

```

{'data': '0x09.........ffffffffffffffffff', 
'gasPrice': 15000000000, 
'to': '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d', 
'value': 0, 
'gas': 27430, 
'nonce': 1294, 
'chainId': 56}

```

**Comment by RichardAtCT** [comment]
Thanks for flagging this @snub-fighter. I have fixed the issue that was stopping build_tx() from properly building an approve transaction. Will include it in my next package update - but for now you can install the package from the github repo to get the working code.

**Comment by snub-fighter** [comment]
Thanks for working together with me on this.
